<?php
/**
 * @file devshop_rancher.module
 */

require 'vendor/autoload.php';

/**
 * Implements hook_menu().
 */
function devshop_rancher_menu() {
  $items = array();

  $items['admin/hosting/rancher'] = array(
    'title' => 'Rancher',
    'description' => 'DevShop Rancher Integration Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devshop_rancher_settings_form'),
    'access arguments' => array('administer projects'),
    'file' => 'includes/admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/hosting/rancher/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/hosting/rancher/hosts'] = array(
    'title' => 'Hosts',
    'description' => 'DevShop Rancher Integration Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devshop_rancher_hosts_form'),
    'access arguments' => array('administer projects'),
    'file' => 'includes/hosts.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_hosting_service_type().
 */
function devshop_rancher_hosting_service_type() {
  return array(
    'rancher' => array(
      'title' => t('Rancher')
    )
  );
}

/**
 * Implements hook_hosting_service()
 * @return array
 */
function devshop_rancher_hosting_service() {
  return array(
    'agent' => 'rancher',
    'server' => 'rancher',
  );
}

/**
 * Implements hook_hosting_servers_titles_alter().
 *
 * Used to make the Rancher server appear in the Web Server select list.
 */
function devshop_rancher_hosting_servers_titles_alter(&$servers, $service) {

  // Load up all rancher agent servers.
  if ($service == 'http' || $service == 'db') {
    $result = db_query("SELECT n.nid, n.title FROM {node} n INNER JOIN {hosting_service} s ON n.vid = s.vid AND s.available = 1 AND s.service = '%s'", 'rancher');
    while ($server = db_fetch_object($result)) {
      $servers[$server->nid] = $server->title;
    }
  }
}

