<?php
/**
 * @file devshop_rancher.module
 */

require 'vendor/autoload.php';

/**
 * Implements hook_menu().
 */
function devshop_rancher_menu() {
  $items = array();

  $items['admin/hosting/devshop/rancher'] = array(
    'title' => 'Rancher',
    'description' => 'DevShop Rancher Integration Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devshop_rancher_settings_form'),
    'access arguments' => array('administer projects'),
    'file' => 'includes/admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}
